version: '2.4'

networks:
  botnet:
    driver: bridge

services:
  seven_bot:
    build: .
    image: seven/bot
    networks:
      - botnet
    container_name: seven_bot
    ports:
      - 80:80
    restart: always
    depends_on:
      - redis

  # db:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
  #     MONGO_INITDB_DATABASE: ${MONGODB_DB}
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./data:/data/db
  #   networks:
  #     - botnet

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    expose:
      - 6379
    container_name: redis_bot
    restart: always
    networks:
      - botnet
